// Command specbundle turns the 7 Days to Die server's multi-file OpenAPI
// spec into a single OpenAPI 3.0.3 document that a Go client generator can
// consume.
//
// Four things make the upstream spec unusable as published: it is split
// across 29 files that $ref each other, three sub-specs key their paths on
// a literal "/BASEPATH/" placeholder the root rewrites, it declares
// OpenAPI 3.1 (whose type-arrays and const keyword Go tooling handles
// unevenly), and it contains outright bugs. See the patches and transforms
// below.
package main

import (
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

const rootName = "openapi.yaml"

// componentSections are merged from every sub-spec into the bundled root.
var componentSections = []string{
	"schemas", "responses", "parameters", "requestBodies", "headers", "examples",
}

func main() {
	from := flag.String("from", "api/snapshot", "snapshot directory, or http(s):// base URL of a live server")
	out := flag.String("out", "api", "output directory")
	tokenName := flag.String("token-name", os.Getenv("SDTD_API_TOKEN_NAME"), "API token name, for -from http")
	tokenSecret := flag.String("token-secret", os.Getenv("SDTD_API_TOKEN_SECRET"), "API token secret, for -from http")
	flag.Parse()

	if err := run(*from, *out, *tokenName, *tokenSecret); err != nil {
		fmt.Fprintln(os.Stderr, "specbundle: "+err.Error())
		os.Exit(1)
	}
}

func run(from, out, tokenName, tokenSecret string) error {
	var files map[string][]byte
	var err error

	if strings.HasPrefix(from, "http://") || strings.HasPrefix(from, "https://") {
		if files, err = fetch(from, tokenName, tokenSecret); err != nil {
			return err
		}
		snapDir := filepath.Join(out, "snapshot")
		if err := os.MkdirAll(snapDir, 0o755); err != nil {
			return err
		}
		for name, b := range files {
			if err := os.WriteFile(filepath.Join(snapDir, name), b, 0o644); err != nil {
				return err
			}
		}
		fmt.Printf("fetched %d spec files into %s\n", len(files), snapDir)
	} else {
		if files, err = readDir(from); err != nil {
			return err
		}
		fmt.Printf("read %d spec files from %s\n", len(files), from)
	}

	docs, err := parseDocs(files)
	if err != nil {
		return err
	}

	applied, err := applyPatches(docs)
	if err != nil {
		return err
	}
	for _, p := range applied {
		fmt.Println("patched: " + p)
	}

	bundled, err := bundle(docs)
	if err != nil {
		return err
	}

	stats := downconvert(bundled)
	fmt.Printf("downconverted to 3.0.3: %d type-arrays, %d null-types, %d const, %d examples, %d status keys, %d ref-siblings\n",
		stats.typeArrays, stats.nullTypes, stats.consts, stats.examples, stats.statusKeys, stats.refSiblings)

	var buf strings.Builder
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(bundled); err != nil {
		return err
	}
	if err := enc.Close(); err != nil {
		return err
	}

	header := "# Generated by tools/specbundle. Do not edit.\n" +
		"# Source: api/snapshot (see api/snapshot/README.md for provenance).\n"
	dst := filepath.Join(out, "openapi.bundled.yaml")
	if err := os.WriteFile(dst, []byte(header+buf.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s (%d bytes)\n", dst, len(buf.String()))
	return nil
}

// ---------- input ----------

var subSpecRef = regexp.MustCompile(`\./([A-Za-z]+)\.openapi\.yaml`)

func fetch(base, tokenName, tokenSecret string) (map[string][]byte, error) {
	base = strings.TrimSuffix(base, "/")
	client := &http.Client{Timeout: 30 * time.Second}

	get := func(path string) ([]byte, error) {
		req, err := http.NewRequest(http.MethodGet, base+path, nil)
		if err != nil {
			return nil, err
		}
		if tokenName != "" {
			req.Header.Set("X-SDTD-API-TOKENNAME", tokenName)
			req.Header.Set("X-SDTD-API-SECRET", tokenSecret)
		}
		resp, err := client.Do(req)
		if err != nil {
			return nil, err
		}
		defer resp.Body.Close()
		if resp.StatusCode != http.StatusOK {
			return nil, fmt.Errorf("GET %s: unexpected status %d", path, resp.StatusCode)
		}
		return io.ReadAll(resp.Body)
	}

	root, err := get("/api/openapi/openapi.yaml")
	if err != nil {
		return nil, err
	}
	files := map[string][]byte{rootName: root}

	seen := map[string]bool{}
	for _, m := range subSpecRef.FindAllStringSubmatch(string(root), -1) {
		seen[m[1]] = true
	}
	names := make([]string, 0, len(seen))
	for n := range seen {
		names = append(names, n)
	}
	sort.Strings(names)

	for _, n := range names {
		b, err := get("/api/OpenAPI/" + n + ".openapi.yaml")
		if err != nil {
			return nil, err
		}
		files[n+".openapi.yaml"] = b
	}
	return files, nil
}

func readDir(dir string) (map[string][]byte, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	files := map[string][]byte{}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".yaml") {
			continue
		}
		b, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			return nil, err
		}
		files[e.Name()] = b
	}
	return files, nil
}

// parseDocs turns raw spec files into their root mapping nodes.
func parseDocs(files map[string][]byte) (map[string]*yaml.Node, error) {
	docs := map[string]*yaml.Node{}
	for name, b := range files {
		var n yaml.Node
		if err := yaml.Unmarshal(b, &n); err != nil {
			return nil, fmt.Errorf("parse %s: %w", name, err)
		}
		if len(n.Content) == 0 {
			return nil, fmt.Errorf("parse %s: empty document", name)
		}
		docs[name] = n.Content[0]
	}
	if docs[rootName] == nil {
		return nil, fmt.Errorf("%s missing from input", rootName)
	}
	return docs, nil
}
