openapi: 3.1.0
info:
  title: Hostile
  version: '1'

components:
  schemas:
    HostileElement:
      type: object
      properties:
        id:
          $ref: './openapi.yaml#/components/schemas/TypeEntityId'
        name:
          type: string
          examples:
            - animalStag
        position:
          $ref: './openapi.yaml#/components/schemas/TypeVector3i'
      required:
        - id
        - name
        - position

    HostileList:
      type: array
      items:
        $ref: '#/components/schemas/HostileElement'


paths:
  /api/hostile:
    get:
      tags:
        - WorldState
      summary: Hostiles list
      description: Fetch a list of the currently spawned hostiles - including hostile animals - in the world
      operationId: Hostile.get
      responses:
        200:
          description: List of hostiles
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/HostileList'
                  meta:
                    $ref: './openapi.yaml#/components/schemas/ResultEnvelopeMeta'
                required:
                  - data
                  - meta
        403:
          $ref: './openapi.yaml#/components/responses/Unauthorized'
      security:
        - apiTokenName: []
          apiTokenSecret: []
        - sessionCookie: []
